version: '3'
services:
  database:
    image: mongo:4.2.9
    ports:
      - 27018:27017
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./volumes/db:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volumes/db:/data/db
volumes:
  mongo_data:
